export const authStatusSelector = state => state.authStatus
export const currentUserSelector = state => state.currentUser
export const matchesSelector = state => state.matches
export const playersSelector = state => state.players
export const tournamentsSelector = state => state.tournaments
export const teamsSelector = state => state.teams
export const currentItemSelector = state => state.currentItem
export const modalOpenSelector = state => state.modalOpen
export const newMatchSelector = state => state.newMatch
export const currentTournamentSelector = state => state.currentTournament
export const navActiveKeySelector = state => state.navActiveKey
